config/routes.rb
Rails.application.routes.draw do
  get 'welcome/news'
  get 'welcome/weather'
  get 'welcome/tasks'
  root 'welcome#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/news_article.rb
class NewsArticle < ApplicationRecord
  require 'get_articles'
  def self.populate_from_api
    require 'pry-byebug';binding.pry
    data = NewsArticleGenerator.get_articles
    data['data'].each do |article|
      tmp_art = NewsArticle.new
      tmp_art.title = article['title']
      tmp_art.description = article['description']
      tmp_art.url = article['url']
      tmp_art.source = article['source']
      tmp_art.save
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/welcome_controller.rb
require 'location'
class WelcomeController < ApplicationController
    def show
      location = get_user_location
      @user_location = location
    end

    def news
      if NewsArticle.first.nil?
        NewsArticle.populate_from_api
      end
      @news = NewsArticle.all
    end

    def weather
    end

    def tasks
    end

    private

    def get_user_location
      ip_address = request.remote_ip
      Location.get_location ip_address
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(path)
    if request.path == path
        return 'active'
    else
        return ''
    end
  end      
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Daily</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'welcome/header' %>
    <%= yield %>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/welcome/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand">Daily</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item <%= active_class(root_path) %>">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item <%= active_class(welcome_news_path) %>">
        <%= link_to 'News', welcome_news_path, class: 'nav-link' %>
      </li>
      <li class="nav-item <%= active_class(welcome_weather_path) %>">
        <%= link_to 'Weather', welcome_weather_path, class: 'nav-link' %>
      </li>
      <li class="nav-item <%= active_class(welcome_tasks_path) %>">
        <%= link_to 'Tasks', welcome_tasks_path, class: 'nav-link' %>
      </li>
    </ul>
    <ul class="nav navbar-nav ml-auto">
      <li> 
        <% if signed_in? %>
        Signed in as: <%= current_user.email %>
        <%= button_to 'Sign out', sign_out_path, method: :delete, class: 'nav-link' %>
        <% else %>
        <%= link_to 'Sign in', sign_in_path, class: 'nav-link' %>
        <% end %>

        <div id="flash">
          <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/welcome/news.html.erb
<div class="row row-cols-1 row-cols-md-3 py-2 ">
  <% @news.each do |article| %>
      <div class="col-md-4 mb-3">
        <div class="card h-100 mx-3 ">
          <div class="card-header"  style="background-color: #a9a9a9;">
            <%= article.title %> 
          </div>
          <div class="card-body" style="background-color: #d3d3d3;">
            <p class="card-text" >Size: <%= article.description %><br> </p>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/welcome/show.html.erb
<%= @user_location[:city] %>